/*
 * This source file was generated by the Gradle 'init' task
 */
package hms;

import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.util.Iterator;
import java.util.UUID;

import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.ss.usermodel.WorkbookFactory;

import hms.controller.Database;
import hms.model.appointment.Appointment;
import hms.model.user.Doctor;
import hms.model.user.Patient;
import hms.view.MainView;

public class App {
    public static void main(String[] args) {
        // Load
        Database.load();

        loadPatientsFromExcel("Patient_List.xlsx");

        Runtime.getRuntime().addShutdownHook(new Thread(new Runnable() {
            public void run() {
                // TODO: Find a way to better save all controllers at once
                Database.save();
            }
        }));

        // Create sample users
        Patient p1 = new Patient("P1", "abc", "first", "patient", "pass", "abc@xyz.com", "+1234");
        Doctor d1 = new Doctor("D1", "cba", "first", "doctor", "pass", "cba@xyz.com", "+1234");
        Appointment a1 = new Appointment(UUID.fromString("00000000-0000-0000-0000-000000000000"), p1, d1, LocalDateTime.of(2024, 11, 19, 10, 0, 0));

        d1.getSchedule().addSlots(LocalDate.of(2024, 11, 19), LocalDate.of(2024, 11, 19), LocalTime.of(07, 0), LocalTime.of(15, 0));

        // Save sample users
        if (Database.getPatient("P1") == null) {
            System.out.println("Creating patient abc...");
            Database.add(p1);
        }
        if (Database.getDoctor("D1") == null) {
            System.out.println("Creating doctor abc...");
            Database.add(d1);
        }
        if (Database.getAppointment(UUID.fromString("00000000-0000-0000-0000-000000000000")) == null) {
            System.out.println("Creating appointment 0...");
            Database.add(a1);
        }

        // Initialise view
        MainView mv = new MainView();
        mv.start();

    }

    public static void loadPatientsFromExcel(String filePath) {
        try {
            FileInputStream file = new FileInputStream(new File(filePath));
            Workbook workbook = WorkbookFactory.create(file);
            Sheet sheet = workbook.getSheetAt(0);

            Iterator<Row> rowIterator = sheet.iterator();

            // Skip first row
            rowIterator.next();

            // Loop through all rows
            while (rowIterator.hasNext()) {
                Row row = rowIterator.next();

                Iterator<Cell> cellIterator = row.cellIterator();

                String patientID = cellIterator.next().getStringCellValue();
                String name = cellIterator.next().getStringCellValue();
                String firstName = name.split(" ")[0]; // TODO: Naive approach
                String lastName = name.split(" ")[1];
                String dateOfBirth = cellIterator.next().getStringCellValue();
                String gender = cellIterator.next().getStringCellValue();
                String bloodType = cellIterator.next().getStringCellValue();
                String contactInformation = cellIterator.next().getStringCellValue();

                // Create new "Patient"
                Patient patient = new Patient(patientID, patientID, firstName, lastName, "defaultPassword", contactInformation, contactInformation, dateOfBirth, gender, bloodType);

                // Check if exists, if not add
                if (Database.getPatient(patientID) == null) {
                    Database.add(patient);
                }
            }
            file.close();
            workbook.close();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}
