/*
 * This source file was generated by the Gradle 'init' task
 */
package sc2002;

import sc2002.view.MainView;

public class HMSApp {
    public static void main(String[] args) {
        // Initialise view
        MainView mv = new MainView();
    }
}
