name: Format Java Code

on:
  push:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - uses: axel-op/googlejavaformat-action@v3
        with:
          args: "--aosp --skip-sorting-imports --replace"
          skip-commit: true

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          title: "ci(lint): formatted all Java codes [skip ci]"
          branch: ci-format
          body: |
            No need to merge constantly, just once in awhile.
          labels: |
            style
            ci
          add-paths: |
            *.java

  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Generate Javadocs
        run: ./gradlew generateDocs

      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3 # or specific "vX.X.X" version tag for this action
        with:
          path: ./app/build/docs/javadoc

 # Deploy job
  deploy-docs:
    needs: build-docs

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 
