name: Format Java Code

on:
  push:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: axel-op/googlejavaformat-action@v3
        with:
          args: "--aosp --skip-sorting-imports --replace"
          skip-commit: true

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          title: "ci(lint): formatted all Java codes [skip ci]"
          branch: ci-format
          body: |
            No need to merge constantly, just once in awhile.
          labels: |
            style
            ci
          add-paths: |
            *.java
